### PR TITLE
Remove deprecated version number from bower.json

### PR DESCRIPTION
**Pull request by huhgawz**

### CODE REVIEW

**Comment by munkychop** [comment]
@huhgawz thanks for the PR. Actually, the `version` field is now deprecated and ignored by Bower in bower.json https://github.com/bower/spec/blob/master/json.md#version

Please remove the `version` field completely and I'll merge your PR.

**Comment by huhgawz** [comment]
e55cc35 Remove `version`

**Comment by munkychop** [comment]
@huhgawz thanks for the contribution 👍

**Comment by huhgawz** [comment]
@munkychop: Certainly, Bower has deprecated the `version` field. However, many libraries out there are still referencing it. Could you revert e55cc35?

**Comment by munkychop** [comment]
@huhgawz I don't get what you mean... why would this being removed affect any other libraries?

**Pull request merged**
